### ISSUE TITLE
有些API已经不可用了

### ISSUE THREAD

**Issue by lucasjinreal** [shuiRong/TodayX#4]
貌似有些url已经不可用了,比如历史上的今天,另外作者是否考虑加入包含图片的历史上的今天api

**Comment by shuiRong** [comment]
@jinfagang 看了下，的确不可用了。
用第三方的API避免不了这种风险，即：不确定什么时候接口就不可用了。

如果接口不可用那就放弃掉这个view吧，或者另行从网上寻找类似的API。

**Comment by lucasjinreal** [comment]
@shuiRong 有合适的推荐吗? 我看大多是只有文字,没有详情和图片的

**Comment by shuiRong** [comment]
看看[这个](https://zhuanlan.zhihu.com/p/87029765)，随手搜到的知乎相关API
